language: node_js
node_js:
  - "8.1.3"
install:
  - npm install -g yarn
  - yarn install
  - cd client
  - yarn install
  - cd ..
  - yarn run build-all
script:
  - yarn run travis
  - cd client
  - yarn run travis